[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Numerov"
version = "0.0.1"

description = "A Python package for calculating Rydberg wavefuntions."
readme = "README.md"
keywords = []

authors = [
    { name = "Johannes Mögerle" },
]

requires-python = ">= 3.9"
dependencies = [
    "numba>=0.60.0",
    "numpy>=2.0.2",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: POSIX :: Linux",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]

[project.optional-dependencies]
tests = [
  "pytest",
  "sympy"
]
dev = [
  "pip",
  "ipykernel",
]

[tool.ruff]
line-length = 120
target-version = "py39"
select = ["F", "E", "B", "C", "W", "I", "UP", "TID25"]
extend-ignore = ["E741", "C901", "B905"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
